### ISSUE TITLE
2.1.0 cannot update by chariz web site

### ISSUE THREAD

**Issue by forpw2009** [L1ghtmann/IAmLazy#26]
i try many times , still cannot download the deb from chariz 
can you release the deb at github site ?
thank you ~

**Comment by L1ghtmann** [comment]
Hey,

Thanks for reaching out. Is there an error? If so, would you mind sharing it here + reaching out to chariz support? Thanks!

**Comment by yueqingyou** [comment]
> Hey,
> 
> Thanks for reaching out. Is there an error? If so, would you mind sharing it here + reaching out to chariz support? Thanks!

I have met the same error
Otherwise, how can I build this tweak?
When I try to build it by theos, it error with 'Managers/IALGeneralManager.m:13:9: fatal error: 'NSTask.h' file not found'
is it the sdks error?
which sdk should I use and where to get?
Many thanks!

**Comment by L1ghtmann** [comment]
What is the Chariz error you see when attempting to update? 

As for the compilation error, download the [NSTask](https://raw.githubusercontent.com/nst/iOS-Runtime-Headers/master/Frameworks/Foundation.framework/NSTask.h) header and place it in $THEOS/include.

**Comment by yueqingyou** [comment]
> What is the Chariz error you see when attempting to update?
> 
> As for the compilation error, download the [NSTask](https://raw.githubusercontent.com/nst/iOS-Runtime-Headers/master/Frameworks/Foundation.framework/NSTask.h) header and place it in $THEOS/include.

when I try to download this tweak in sileo, chariz shows waiting always and can't download success

**Comment by L1ghtmann** [comment]
Interesting. I'd try another package manager like Zebra and if that still fails try reaching out to Chariz support

**Comment by forpw2009** [comment]
hi , maybe MD5 is  different ~ though we have download it but the MD5 verification failed

**Comment by L1ghtmann** [comment]
Okay, in that case I'd recommend you contact their support -- https://hashbang.productions/support/. They'll be better able to assist you

**Comment by forpw2009** [comment]
OK, I have mailed them , if this problem is sloved , i will share it to you ~
thank you ~

**Comment by kane159** [comment]
I also have this issue
it shows the size error expected size 158722 actual size 158768
![30D9B509-BBA3-45F8-A54E-A7B37BA77DBE](https://user-images.githubusercontent.com/4179610/189598583-8c6fad89-bef6-4add-8964-a97a0521f098.png)

**Comment by yueqingyou** [comment]
> I also have this issue
> it shows the size error expected size 158722 actual size 158768
> ![30D9B509-BBA3-45F8-A54E-A7B37BA77DBE](https://user-images.githubusercontent.com/4179610/189598583-8c6fad89-bef6-4add-8964-a97a0521f098.png)

Too slow to deal with problems hhh

**Comment by L1ghtmann** [comment]
@forpw2009 did you manage to get this resolved?

**Comment by L1ghtmann** [comment]
> I also have this issue
> 
> it shows the size error expected size 158722 actual size 158768
> 
> ![30D9B509-BBA3-45F8-A54E-A7B37BA77DBE](https://user-images.githubusercontent.com/4179610/189598583-8c6fad89-bef6-4add-8964-a97a0521f098.png)
> 
> 

If you're having issues downloading it, I'd reach out to chariz support (linked above) to see if they can provide some guidance with how to proceed. Apologies for the trouble.

**Comment by yueqingyou** [comment]
> > I also have this issue
> > it shows the size error expected size 158722 actual size 158768
> > ![30D9B509-BBA3-45F8-A54E-A7B37BA77DBE](https://user-images.githubusercontent.com/4179610/189598583-8c6fad89-bef6-4add-8964-a97a0521f098.png)
> 
> If you're having issues downloading it, I'd reach out to chariz support (linked above) to see if they can provide some guidance with how to proceed. Apologies for the trouble.

oh sorry i think you misunderstood me
What I'm complaining about is the processing speed of the chariz repo
The cause of the problem is not yours
sorry for misunderstanding you

**Comment by L1ghtmann** [comment]
@kane159 @yueqingyou @forpw2009 the issue should be resolved now. Would you mind trying again to confirm? Thanks!

**Comment by yueqingyou** [comment]
> @kane159 @yueqingyou @forpw2009 the issue should be resolved now. Would you mind trying again to confirm? Thanks!

When I try to install with sileo it still fails and I have refreshed the repo
I tried to switch to zebra and everything works fine

**Comment by iAdam1n** [comment]
Can you try refreshing and try again now please?

**Comment by L1ghtmann** [comment]
This should be resolved now. If it's not, feel free to reopen.

**Comment by forpw2009** [comment]
亲，您的邮件我收到啦！
